### ISSUE TITLE
리팩토링 및 버그 수정

### ISSUE THREAD

**Issue by solo5star** [deu-meta/metaland-accounts#100]
## Summary
* 리팩토링 및 버그 수정

## TODO
- [x] `InternalServerError` 줄이기 - `raise ex.예외클래스` 를 `raise ex.예외클래스()` 로 수정하여 실제 오류를 Front-end에 전달
- [x] `init.db` 파일에서 `CREATE TABLE` 에서 선언할 수 있는 `PRIMARY KEY`, `FOREIGN KEY` 는 `CREATE TABLE` 에 넣기
- [x] `users.email` `INDEX` 추가
- [x] `Users` sqlalchemy 모델에서 `id`, `email` 필드의 `primary_key` 가 잘못 적용되어있는 오류 수정하기
- [x] `APIException` 의 `msg` 필드들을 모두 `message` 로 수정 (FastAPI에서 `message` 외엔 인식을 잘 못하는 듯함)
- [x] 클래스 이름에서 `Ex` 대신 `Exception` 사용 (`ex` 는 주로 `try ... except` 에서 일회성으로 자주 사용되며 클래스 이름에서는 잘 사용하지 않음)
- [x] `Authorize.create_access_token` 에서 `user_claim`으로 json을 넣을 때 `datetime`이 들어갈 경우 발생하는 오류 수정하기
- [x] OAuth 2.0 과 관련된 환경변수중에서, `REDIRECT_URL` 을 `REDIRECT_URI` 로 수정
- [x] 카카오 OAuth 2.0 에서 `client_secret` 추가
- [x] 카카오 OAuth 2.0 에서 `client_secret` 이 전달되지 않는 오류 수정
- [x] Microsoft SSO의 scope에 `email`, `profile` 추가

## References
*None*
