### ISSUE TITLE
간단한 버그 수정

### ISSUE THREAD

**Issue by solo5star** [deu-meta/metaland-accounts#104]
## Summary
* 사소한 버그들 수정

## TODO
- [x] 이메일을 PK로 쓰는 코드들 수정
- [x] `openid` 로 DB에서 사용자를 찾을 때 `provider` 와 `email` 둘 다 사용하여 찾도록 수정
- [x] `/users` 에서 `get_profile` 코드 수정

## References
*None*
